### ISSUE TITLE
Incompatibility with some mods expecting `BuildSettingList` to be public

### ISSUE THREAD

**Issue by nbusseneau** [shudnal/ConfigurationManager#1]
Hey,

So this is a very weird incompatibility, but basically some mods expect the `BuildSettingList` public method to be present in the config manager because they manually interact with it, e.g. [here's an example with PlantEasily](https://github.com/AdvizeGH/Advize_ValheimMods/blob/e03b6acc83f7203a1775274d3c3efe3d9e624b43/Advize_PlantEverything/Configuration/ModConfig.cs#L1343). I have also noticed this happening with other mods such as CreatureLevelAndLootControl and Passive Powers, and I would not be surprised it happens with other mods I don't use but that happened to copy/paste the same bit of code.

In your revised configuration manager `BuildSettingList` still exists but is private, which logically results in the following issues because reflection does not find the method without the private binding flag set:

```
[Error  :   BepInEx] System.NullReferenceException: Object reference not set to an instance of an object
  at CreatureLevelControl.CreatureLevelControl+<>c__DisplayClass144_0.<Awake>g__reloadConfigDisplay|0 () [0x00020] in <70b479e9cdcd4e3dbe208f17873bfc82>:0 
  at CreatureLevelControl.CreatureLevelControl+<>c__DisplayClass144_0.<Awake>b__11 (System.Object _, System.EventArgs _) [0x00088] in <70b479e9cdcd4e3dbe208f17873bfc82>:0 
  at (wrapper delegate-invoke) <Module>.invoke_void_object_EventArgs(object,System.EventArgs)
  at BepInEx.Configuration.ConfigEntry`1[T].<.ctor>b__10_0 (System.Object sender, BepInEx.Configuration.SettingChangedEventArgs args) [0x00013] in <5e471ddbeb974684bff43bc61f1b58cb>:0 
  at BepInEx.Configuration.ConfigFile.OnSettingChanged (System.Object sender, BepInEx.Configuration.ConfigEntryBase changedEntryBase) [0x00048] in <5e471ddbeb974684bff43bc61f1b58cb>:0 
```

It's a bit annoying because on one hand what the mods try to do is not very robust and probably it would make sense to open reports for each of them individually to get them to change this, on the other hand it seems this bit of code has "infected" a good number of mods including big ones, so I figured reporting it here would also makes sense because I suspect you might want your mod to play nice with as many mods as possible :D

**Comment by shudnal** [comment]
Fixed in 1.0.8.
My fork is not based on very late version so it could something that changed since. If you stumple upon something similar I'll fix that.

**Comment by nbusseneau** [comment]
I had a quick look at commits history just out of curiosity and it looks like the change was introduced in 4811fd1c50ab1b64c60c15d0437556d6445254bb, as part of moving the function from `ConfigurationManager.cs` to `SettingsWindow.cs`. I will definitely let you know if I happen to stumble onto something similar in the future, cheers :)

**Comment by shudnal** [comment]
I think I know what was going in my mind. Although method was public but it had no summary like others so I thought it's just an oversight. The method is really didn't look like something that should be called externally.

**Comment by nbusseneau** [comment]
Yeah it actually probably is not supposed to anyway, and just happened to be picked by blaxxun / Smoothbrain and then trickled down into other mods (since many mods take inspiration from their mods).
