### ISSUE TITLE
"Configuration version must not be higher than 1.0.7, you have 1.0.8"

### ISSUE THREAD

**Issue by rudnuh** [shudnal/ConfigurationManager#2]
Started getting this error after updating the mod today :(

![image](https://github.com/shudnal/ConfigurationManager/assets/171618498/9f267592-7c65-42b2-a31f-bdd3a7caf92b)

**Comment by shudnal** [comment]
It means your server is running 1.0.7 and your client is 1.0.8.
You either rollback to 1.0.7 version on your client or update the server version to 1.0.8.
