### ISSUE TITLE
Spam errors when typing in search field.

### ISSUE THREAD

**Issue by Sketaful** [shudnal/ConfigurationManager#5]
Sorry, don't have any logs or anything. Had to remove the mod and after that my log is gone cause I took some time.

But just like, as a notice, and if you somehow actually already know of it and why...

When typing in the search window the console go bananas with errors. It still do the search as slowly as it can (like all configurators seem to do) but it really doesn't seem to like it.

**Comment by shudnal** [comment]
It's either some mod failing to draw custom field or mod trying to access some that mod property via reflection.
Without the error text or conflicting mod name it's nothing I can do.

**Comment by Sketaful** [comment]
Ok. Prob nothing game breaking atleast? :)
Thanks for answering. I will go through the mods and see if I can figure out which one(s) behind it. :)

**Comment by shudnal** [comment]
It's much easier to find error text first.

**Comment by shudnal** [comment]
Nothing game breaking but without info there is nothing to fix.
