### ISSUE TITLE
Some mod configs incomplete 

### ISSUE THREAD

**Issue by MrBungled** [shudnal/ConfigurationManager#6]
Good day 

love your mod , beautiful and works great. I had used another config manager prior to yours. I’ve noticed since switching to your config manager that some config options aren’t available anymore in the F1 window. 

As an example I use the mod called teleport everything, in its config you can set portal activation distance and sound level of portal. In your manager those are not available. 

Thanks again for your great work. I just wanted to inform that there are some incomplete configurations for F1 

Cheers 

MrBungles

**Comment by shudnal** [comment]
I have no idea why mod author made this extra configs marked Advanced.
Advanced checkbox is false by default. You have to enable it in Configuration Manager header to make them appear.

**Comment by MrBungled** [comment]
Oh ok , never noticed the advanced check box .

Will check it out

Thanks got the quick response

Much appreciated

On Jul 11, 2024, at 9:02 AM, Suden ***@***.***> wrote:

﻿

I have no idea why mod author made this extra configs marked Advanced.
Advanced checkbox is false by default. You have to enable it in Configuration Manager header to make them appear.
